version: "3"
services:
  api:
    build:
      context: ./api
    image: schinkenspicker.azurecr.io/bib/api
    environment:
      PORT: 4000
      MONGO_URI: ${MONGO_URI}

  frontend:
    build:
      context: ./frontend
    image: schinkenspicker.azurecr.io/bib/frontend
    depends_on:
      - api
    environment:
      API_HOST: api
      API_PORT: 4000
    ports:
      - "80:80"
