# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
       working-directory: ./application
           
    strategy:
      matrix:
        node-version: [14.x]
        project: [frontend, api]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './application/${{ matrix.project }}/package-lock.json'
        
    - run: npm ci
      working-directory: './application/${{ matrix.project }}'
    - run: npm run build --if-present
      working-directory: './application/${{ matrix.project }}'
    - run: npm test
      working-directory: './application/${{ matrix.project }}'


  build:
    needs: test
  
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        project: [frontend, api, db-seed]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: 'application/${{ matrix.project }}'
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.project }}:${{ github.sha }}
      
